### ISSUE TITLE
Assertion error with T56 using version.py

### ISSUE THREAD

**Issue by tbejos** [JohnDMcMaster/libxgecu#1]
When attempting to use version.py I repeatedly get an error with length of buff and old when using a T56 (was last used with Xgpro 11.81 with firmware V .1.55)
```
tbejos@ThinkPad-P50:~/workspace/libxgecu/t48$ sudo python3 version.py tbejos.bin
Scanning for devices...
Found device
Bus 001 Device 006: ID a466:0a53
Traceback (most recent call last):
  File "version.py", line 21, in <module>
    main()
  File "version.py", line 14, in main
    raw = t.version_raw()
  File "/home/tbejos/workspace/libxgecu/t48/xgecu/t48.py", line 59, in version_raw
    assert len(buff) == len(old)
AssertionError
```

I tried updating the firmware with Xgpro 12.39 to firmware V .1.65 but that did not resolve the issue.
I have printed `buff` and `old` to compare and included them below.
    
Old: 
`b'\x00\x010\x00\x03\x01\x07\x002022-09-2109:27\x0029A03632WDN5YFOMK2RRVJ0A2F9S9613\x1f\x06\x00\x00\x01\x00\x00'`

Buff (V .1.55):
`b'\x00\x010\x007\x01\x06\x002021-10-08 00:3713201079093LW9RV6KEUS5VES69XR5O6\xf3\x05\x00\x00\x01\x00\x00\x00'`

Buff (V .1.65)
`b'\x00\x010\x00A\x01\x06\x002021-10-08 00:3713201079093LW9RV6KEUS5VES69XR5O6\xf3\x05\x00\x00\x01\x00\x00\x00'`

**Comment by JohnDMcMaster** [comment]
Hi there! This was never tested with T56, although we do know they are similar. TBH I'm surprised it even matched the USB VID / PID. In any case it seems like what you've discovered is that both T48 and T56 use the same VID / PID but slightly different version info structure. You have enough info there where I can take a look how the structures differ

We are definitely going to focus on T48 for a bit though before really putting effort into T56. If you do want to join the dev effort directly though email me and I can give you a link to the sipr0n discord where there is a dedicated channel

**Comment by tbejos** [comment]
Understood, I saw a lot of references to only the T48 so kind of assumed it was something like that but saw the post on the minipro gitlab and saw that the readme mentions T56 so figured I'd give it a try, just sent an email reaching out as well.

**Comment by JohnDMcMaster** [comment]
I've updated the software to support T56. Should be good now
